// Automatically generated by MockGen. DO NOT EDIT!
// Source: router.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Pather interface
type MockPather struct {
	ctrl     *gomock.Controller
	recorder *_MockPatherRecorder
}

// Recorder for MockPather (not exported)
type _MockPatherRecorder struct {
	mock *MockPather
}

func NewMockPather(ctrl *gomock.Controller) *MockPather {
	mock := &MockPather{ctrl: ctrl}
	mock.recorder = &_MockPatherRecorder{mock}
	return mock
}

func (_m *MockPather) EXPECT() *_MockPatherRecorder {
	return _m.recorder
}

func (_m *MockPather) Path(name string) string {
	ret := _m.ctrl.Call(_m, "Path", name)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockPatherRecorder) Path(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Path", arg0)
}
